
return {
  enabled = false,
  mode = 'assist',
  leader = '',
  follow = true,
  follow_distance = 3.6,
  ws = 'Fast Blade',
  tp = 1000,
  auto_ws_by_weapon = true,
  heal_threshold = 60,
  cure_spell = 'Cure III',
  min_mp = 60,
  auto_cure_tier = true,
  pulse = 0.25,
  pld = {
    use_flash = true,    flash_cd = 25.0,
    use_provoke = true,  provoke_cd = 30.0,
    use_sentinel = true, sentinel_cd = 300.0, panic_hpp = 35,
    use_rampart = true,  rampart_cd = 300.0,
    use_shield_bash = true, shield_bash_cd = 45.0,
    keep_reprisal = true, reprisal_cd = 60.0,
    keep_enlight = true, enlight_cd = 240.0,
    keep_majesty = true, majesty_cd = 60.0,
    self_cure_hpp = 70,  cure_cd = 8.0,
    buff_awareness = true,
    use_cover = true, cover_cd = 180.0, cover_hpp = 50, cover_distance = 10.0,
    cover_mode = 'highest_hate', cover_stepin = true, cover_step_time = 2.5,
    hate_reset_window = 2.0, buff_duration_aware = true,
    reprisal_refresh = 50, enlight_refresh = 110, majesty_refresh = 55,
  },
  war = {
    enable = true,
    stance = 'defensive',
    use_berserk = true,     berserk_cd = 300.0,
    use_defender = true,    defender_cd = 300.0,
    use_aggressor = false,  aggressor_cd = 300.0,
    use_warcry = true,      warcry_cd = 300.0,
    auto_defender_hpp = 85,
  },
  hud = { enable = true, x = 20, y = 60, size = 12, hatebar = true, bar_width = 20, cooldowns = true, cd_width = 8, color = true },
  smooth = { enable = true, move_delay = 0.35, target_switch_delay = 0.6 },
}
